-- 드니네 책장(홈 보유 원서) 테이블 + 데이터 (Supabase SQL Editor 에서 Run)
create table if not exists public.home_books (
  id bigint generated always as identity primary key,
  series text, title text, age text, pref text, sort int default 0);
alter table public.home_books enable row level security;
drop policy if exists "public read home_books" on public.home_books;
create policy "public read home_books" on public.home_books for select using (true);
drop policy if exists "admin write home_books" on public.home_books;
create policy "admin write home_books" on public.home_books for all using (public.is_admin()) with check (public.is_admin());
delete from public.home_books;

insert into public.home_books(series,title,age,pref,sort) values ('David','Oops!','12개월~24개월','',0);
insert into public.home_books(series,title,age,pref,sort) values ('David','Oh, David!','12개월~24개월','',1);
insert into public.home_books(series,title,age,pref,sort) values ('David','DAVID SMELLS!','12개월~24개월','',2);
insert into public.home_books(series,title,age,pref,sort) values ('David','No, David!','12개월~24개월','6',3);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','10 Button Book','12개월~24개월','4',4);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Color Zoo','12개월~24개월','5',5);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Helen Oxenbury''s Big Baby Book','12개월~24개월','1',6);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Lemons Are Not Red','12개월~24개월','6',7);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Whose Baby Am I?','12개월~24개월','1',8);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','A parade of Elephants','12개월~24개월','1',9);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Does a Kangaroo Have a Mother, Too?','12개월~24개월','1',10);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Night Night, Little Green Monster','12개월~24개월','6',11);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Noisy Peekaboo! Choo! Choo!','12개월~24개월','5',12);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Splish, SPlash, Ducky!','12개월~24개월','1',13);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Goodnight Moon','12개월~24개월','5',14);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Baby''s Busy World','12개월~24개월','4',15);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Welcome, Baby!','12개월~24개월','1',16);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Hush Little Baby','12개월~24개월','3',17);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베이비','Nursery Rhymes','12개월~24개월','3',18);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 에릭칼','Brown Bear, Brown Bear, What Do You See?','12개월~24개월','1',19);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 에릭칼','The Very Busy Spider','12개월~24개월','1',20);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 에릭칼','Polar Bear, Polar Bear, What Do you See?','12개월~24개월','1',21);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 에릭칼','Baby Bear, Baby Bear, What Do you See?','12개월~24개월','1',22);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 에릭칼','Panda Bear, Panda Bear, What Do you See?','12개월~24개월','1',23);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot Goes to the Farm','12개월~36개월','3',24);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot Bakes a Cake','12개월~36개월','3',25);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot Goes on Holiday','12개월~36개월','3',26);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot Goes to the Park','12개월~36개월','3',27);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot Goes to School','12개월~36개월','3',28);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot Stays Overnight','12개월~36개월','3',29);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot''s Birthday Party','12개월~36개월','3',30);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Who''s there, Spot?','12개월~36개월','3',31);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Where''s Spot?','12개월~36개월','3',32);
insert into public.home_books(series,title,age,pref,sort) values ('SPOT','Spot Says Goodnight','12개월~36개월','3',33);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy''s Bathtime','24개월~5세','',34);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy Tidies Up','24개월~5세','5',35);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy Makes Lemonade','24개월~5세','',36);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy Goes Shopping','24개월~5세','',37);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy Dresses Up','24개월~5세','',38);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy''s Pool','24개월~5세','',39);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Doctor Maisy','24개월~5세','',40);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','maisy''s Bedtime','24개월~5세','',41);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy''s Bus','24개월~5세','',42);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy Story Book','Maisy Makes Gingerbread','24개월~5세','',43);
insert into public.home_books(series,title,age,pref,sort) values ('Eric Carle','From Head to Toe','24개월~5세','',44);
insert into public.home_books(series,title,age,pref,sort) values ('Eric Carle','The Very Hungry Caterpillar','24개월~5세','4',45);
insert into public.home_books(series,title,age,pref,sort) values ('노부영','Today is Monday','24개월~5세','6',46);
insert into public.home_books(series,title,age,pref,sort) values ('노부영','Quick as a Cricket','24개월~5세','',47);
insert into public.home_books(series,title,age,pref,sort) values ('노부영','THE BIG HUNGRY BEAR','24개월~5세','',48);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Inside Outside Upside Down','24개월~5세','6',49);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','the Spooky Old Tree','24개월~5세','6',50);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Go, Dog. Go!','24개월~5세','',51);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Big Dog... Little Dog','24개월~5세','',52);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','I''ll Teach My Dog a Lot of Words','24개월~5세','',53);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Hand, Hand, Fingers, Thumb','24개월~5세','3',54);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','The Alphabet Book','24개월~5세','',55);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Are You My Mother?','24개월~5세','',56);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','He Bear, She Bear','24개월~5세','',57);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Fred and Ted like to Fly','24개월~5세','',58);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Old Hat New Hat','24개월~5세','',59);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 닥터수스','Put Me in the Zoo','24개월~5세','',60);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','Hooray for Fish!','24개월~5세','2',61);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','Go Away, Big Green Monster!','24개월~5세','6',62);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','Me! Me! ABC','24개월~5세','6',63);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','Monster, Monster','24개월~5세','6',64);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','One Gorilla','24개월~5세','2',65);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','Walking Through the Jungle','24개월~5세','1',66);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','We All Go Traveling By','24개월~5세','1',67);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','Go Away Mr Wolf!','24개월~5세','5',68);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','The Great Big Enormous Turnip','24개월~5세','6',69);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','How Do You Feel?','24개월~5세','3',70);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','I Am the Music Man','24개월~5세','3',71);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','The Wheels on the Bus Go Round and Round','24개월~5세','1',72);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','I''m the Best','24개월~5세','1',73);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','Dry Bones','24개월~5세','5',74);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 베스트','The Animal Boogie','24개월~5세','1',75);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 에릭칼','The Very Quiet Cricket','24개월~5세','1',76);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','Dr.Seuss''s 123','24개월~5세','',77);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','Dr.Seuss''s Book of COLORS','24개월~5세','',78);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','HOP on POP','24개월~5세','',79);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','The Tooth book','24개월~5세','',80);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','The Nose Book','24개월~5세','',81);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','Oh ther Thinks you can Think!','24개월~5세','6',82);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','There''s Wocket in my Pocket!','24개월~5세','',83);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','Ten Apples Up On Top!','24개월~5세','',84);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','Dr.Seuss''s ABC','24개월~5세','',85);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','The Foot book','24개월~5세','',86);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','The Eye Book','24개월~5세','',87);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','The Shape of Me and OTHER STUFF','24개월~5세','',88);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','Mr. Brown Can Moo! Can you?','24개월~5세','',89);
insert into public.home_books(series,title,age,pref,sort) values ('닥터수스','Fox in Socks','24개월~5세','',90);
insert into public.home_books(series,title,age,pref,sort) values ('단권','My World','24개월~5세','',91);
insert into public.home_books(series,title,age,pref,sort) values ('단권','ZOE and ZACK SHAPES','24개월~5세','3',92);
insert into public.home_books(series,title,age,pref,sort) values ('단권','IN MY WORLD','24개월~5세','5',93);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Biscuit Goes to the Park','24개월~5세','1',94);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Underwear!','24개월~5세','5',95);
insert into public.home_books(series,title,age,pref,sort) values ('단권','THIS LITTLE CAT','24개월~5세','',96);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Copy Cat','','',97);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','What Do you See?','','',98);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Bath Time','','',99);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Nice Wheels','','',100);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Wait for Me!','','',101);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','I can Read!','','',102);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','A Bear for you','','',103);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','What TIme is it?','','',104);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','My Pumpkin','','',105);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Ah-choo!','','',106);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Step-by-step','','',107);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','My New Town','','',108);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','My Best Friend','','',109);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','I am smart','','',110);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','The Very Bad Day','','',111);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','The Big Game','','',112);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Grandma''s House','','',113);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Zoom, Zoom, Zoom','','',114);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','The New Baby','','',115);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Guess Who?','','',116);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','Pick a Pet','','',117);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','My New School','','',118);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','The Weather','','',119);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','A Day with Daddy','','',120);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 2','I Am Sick','','',121);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Boats, Boats, Boats','','',122);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','My House','','',123);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Surprise','','',124);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Where is Jake?','','5',125);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','LIttle Bear','','',126);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Who says?','','',127);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Dog and Cat','','',128);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Monsters!','','5',129);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','The Kite','','',130);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','The Mess','','',131);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Bunny, Bunny','','',132);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Good Night, Little Kitten','','',133);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','I''m a Princess','','',134);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','I''m not scared','','',135);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Sleep-over Mouse','','',136);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Ballerina Girl','','',137);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','The Tooth Fairy','','',138);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','I Am King!','','',139);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','My Trucks','','',140);
insert into public.home_books(series,title,age,pref,sort) values ('My First Book 1','Duck, Duck, Goose!','','',141);
insert into public.home_books(series,title,age,pref,sort) values ('단권','MY MUM','24개월~5세','',142);
insert into public.home_books(series,title,age,pref,sort) values ('단권','My Presents','24개월~5세','5',143);
insert into public.home_books(series,title,age,pref,sort) values ('단권','MY DAD','24개월~5세','',144);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Clifford - the Big Red Dog','24개월~5세','1',145);
insert into public.home_books(series,title,age,pref,sort) values ('단권','THE WATERMELON SEED','24개월~5세','5',146);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Chicka Chicka Boom Boom','24개월~5세','4',147);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Hey, Poopie Holders!','24개월~5세','5',148);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Hey, Booger Diggers!','24개월~5세','',149);
insert into public.home_books(series,title,age,pref,sort) values ('단권','bear at home','24개월~5세','',150);
insert into public.home_books(series,title,age,pref,sort) values ('단권','bear in sunshine','24개월~5세','',151);
insert into public.home_books(series,title,age,pref,sort) values ('단권','bear about town','24개월~5세','',152);
insert into public.home_books(series,title,age,pref,sort) values ('단권','One Gorilla - ANTHONY BROWNE','24개월~5세','',153);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Alphabatics','24개월~5세','',154);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy''s Christmas Eve','36개월~6세','',155);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Plays Soccer','36개월~6세','',156);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy, Charly and the Wobbly Tooth','36개월~6세','',157);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes by Plane','36개월~6세','',158);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes to Hospital','36개월~6세','',159);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes to th Library','36개월~6세','',160);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes Camping','36개월~6세','',161);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes to the Museum','36개월~6세','',162);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes on a Sleepover','36개월~6세','',163);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy learns to Swim','36개월~6세','',164);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes to the Movies','36개월~6세','',165);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes to Nursery','36개월~6세','',166);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes to the City','36개월~6세','',167);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy Goes on Holiday','36개월~6세','',168);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','What''s Inside?','','',169);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','What''s missing?','','',170);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','What''s the Difference?','','',171);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Peek-A-Boo!','','',172);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Tell Me Which','','',173);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','It''s Me!','','',174);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Where Am I?','','',175);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','One or Many','','',176);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','My Birth','','',177);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Discovers','','',178);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Time to Eat','','',179);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Time for a Bath','','',180);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Play Time!','','',181);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','That Smells Good!','','',182);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','My Favorite Colors!','','',183);
insert into public.home_books(series,title,age,pref,sort) values ('Caillou','Loot At me!','','',184);
insert into public.home_books(series,title,age,pref,sort) values ('A Maisy First Experiences Book','Maisy''s Field Day','36개월~6세','',185);
insert into public.home_books(series,title,age,pref,sort) values ('Peppa Pig','Muddy Festival','36개월~6세','4',186);
insert into public.home_books(series,title,age,pref,sort) values ('Peppa Pig','Trip to London','36개월~6세','',187);
insert into public.home_books(series,title,age,pref,sort) values ('Peppa Pig','Tiny Land','36개월~6세','',188);
insert into public.home_books(series,title,age,pref,sort) values ('Peppa Pig','Snowy Mountain','36개월~6세','',189);
insert into public.home_books(series,title,age,pref,sort) values ('Peppa Pig','Grandpa Pig''s Birthday','36개월~6세','',190);
insert into public.home_books(series,title,age,pref,sort) values ('Peppa Pig','Muddy Puddles','36개월~6세','',191);
insert into public.home_books(series,title,age,pref,sort) values ('Peppa Pig','Petting Zoo','36개월~6세','',192);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Piggies','36개월~6세','5',193);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Bugs! Bugs! Bugs!','36개월~6세','1',194);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','The Chick and the Duckling','36개월~6세','1',195);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Cleo''s Alphabet Book','36개월~6세','1',196);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Dear Zoo','36개월~6세','6',197);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Dinosaur Roar!','36개월~6세','1',198);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Five Little Monkeys Jumping On the Bed','36개월~6세','1',199);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','The Little Bear Book','36개월~6세','5',200);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','See You Later, Alligator!','36개월~6세','3',201);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','What''s the Time, Mr, Wolf?','36개월~6세','4',202);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Who Stole the Cookies from the Cookie jar?','36개월~6세','6',203);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','A Hole in the Bottom of the Sea','36개월~6세','6',204);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Up, Up, Up!','36개월~6세','6',205);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','What Am I?','36개월~6세','6',206);
insert into public.home_books(series,title,age,pref,sort) values ('노부영 스테디','Skip through the Seasons','36개월~6세','4',207);
insert into public.home_books(series,title,age,pref,sort) values ('CHRIS HAUGHTON','GOODNIGHT EVERYONE','5세~7세','',208);
insert into public.home_books(series,title,age,pref,sort) values ('CHRIS HAUGHTON','A Bit Lost','5세~7세','',209);
insert into public.home_books(series,title,age,pref,sort) values ('CHRIS HAUGHTON','Shh! We have a Plan','5세~7세','4',210);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','My Friend Is Sad','5세~7세','',211);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','I am Invited to a Party!','5세~7세','',212);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','I Broke my Trunk!','5세~7세','',213);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','Today I Will Fly!','5세~7세','',214);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','Watch me throw the Ball!','5세~7세','',215);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','Let''s go for a Drive!','5세~7세','',216);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','I Love My New Toy!','5세~7세','',217);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','Are you Ready to play outside?','5세~7세','',218);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','I will Surprise My Friend!','5세~7세','',219);
insert into public.home_books(series,title,age,pref,sort) values ('Elephant and Piggie','There is a bird on you head!','5세~7세','',220);
insert into public.home_books(series,title,age,pref,sort) values ('Eric Carle','Pancake! Pancake!','5세~7세','6',221);
insert into public.home_books(series,title,age,pref,sort) values ('Eric Carle','The Foolish Tortoise','5세~7세','',222);
insert into public.home_books(series,title,age,pref,sort) values ('Eric Carle','The Greedy Python','5세~7세','',223);
insert into public.home_books(series,title,age,pref,sort) values ('Eric Carle','A House for Hermit Crab','5세~7세','',224);
insert into public.home_books(series,title,age,pref,sort) values ('Eric Carle','THE GROUCHY LADYBUF','5세~7세','',225);
insert into public.home_books(series,title,age,pref,sort) values ('KNUFFLE BUNNY','KNUFFLE BUNNY','5세~7세','5',226);
insert into public.home_books(series,title,age,pref,sort) values ('KNUFFLE BUNNY','KNUFFLE BUNNY TOO','5세~7세','',227);
insert into public.home_books(series,title,age,pref,sort) values ('KNUFFLE BUNNY','KNUFFLE BUNNY FREE','5세~7세','',228);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Hungry Hen','5세~7세','2',229);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Smile Crocodile Smile','5세~7세','3',230);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The loudest Roar','5세~7세','4',231);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Biggest Splash','5세~7세','',232);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Wee William','5세~7세','',233);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Beautiful Bananas','5세~7세','',234);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The Scary Monster','5세~7세','',235);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The little puddle','5세~7세','',236);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The bedtime frog','5세~7세','',237);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The Snowy Day','5세~7세','',238);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The Big Ballon','5세~7세','',239);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The Christmas Tree','5세~7세','',240);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The Super Scooter','5세~7세','',241);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The New Friend','5세~7세','',242);
insert into public.home_books(series,title,age,pref,sort) values ('Pip and Posy','The Friendly Snail','5세~7세','',243);
insert into public.home_books(series,title,age,pref,sort) values ('ten minutes to bed','Little Unicorn','5세~7세','',244);
insert into public.home_books(series,title,age,pref,sort) values ('ten minutes to bed','Little Dinosaur','5세~7세','',245);
insert into public.home_books(series,title,age,pref,sort) values ('ten minutes to bed','Baby Unicorn','5세~7세','',246);
insert into public.home_books(series,title,age,pref,sort) values ('ten minutes to bed','Little Dragon','5세~7세','',247);
insert into public.home_books(series,title,age,pref,sort) values ('ten minutes to bed','Little Fairy','5세~7세','',248);
insert into public.home_books(series,title,age,pref,sort) values ('단권','I Ain''t Gonna Paint No More!','5세~7세','5',249);
insert into public.home_books(series,title,age,pref,sort) values ('단권','PENGUIN','5세~7세','',250);
insert into public.home_books(series,title,age,pref,sort) values ('단권','THERE WAS AN OLD LADY WHO SWALLOWED A FLY','5세~7세','5',251);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Madlenka','5세~7세','',252);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Shark in the Park!','5세~7세','',253);
insert into public.home_books(series,title,age,pref,sort) values ('단권','POOH! Is that you, Bertie?','5세~7세','',254);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Noisy night','5세~7세','',255);
insert into public.home_books(series,title,age,pref,sort) values ('단권','how rude!','5세~7세','',256);
insert into public.home_books(series,title,age,pref,sort) values ('단권','going to the volcano','5세~7세','',257);
insert into public.home_books(series,title,age,pref,sort) values ('단권','triangle','5세~7세','',258);
insert into public.home_books(series,title,age,pref,sort) values ('단권','I want my hat back','5세~7세','',259);
insert into public.home_books(series,title,age,pref,sort) values ('단권','there''s no such thing as unicorns','5세~7세','',260);
insert into public.home_books(series,title,age,pref,sort) values ('단권','there''s no such thing as mermaids','5세~7세','',261);
insert into public.home_books(series,title,age,pref,sort) values ('단권','not now Bernard','5세~7세','',262);
insert into public.home_books(series,title,age,pref,sort) values ('단권','the bikini bottom bike race','5세~7세','',263);
insert into public.home_books(series,title,age,pref,sort) values ('단권','frosty''s new friends','5세~7세','',264);
insert into public.home_books(series,title,age,pref,sort) values ('단권','the noisy attic (minnie misteries)','5세~7세','',265);
insert into public.home_books(series,title,age,pref,sort) values ('단권','PETE''S A PIZZA','5세~7세','',266);
insert into public.home_books(series,title,age,pref,sort) values ('단권','Guess How Much I Love You','5세~7세','',267);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur Breaks the Bank','6세~7세','',268);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur Lost in the Museum','6세~7세','',269);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur, Clean Your Room!','6세~7세','',270);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur''s Reading Race','6세~7세','',271);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur and the New Kid','6세~7세','',272);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur in a pickle','6세~7세','',273);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur''s Reading Trick','6세~7세','',274);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Glasses for D.W','6세~7세','',275);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur''s Hiccups','6세~7세','',276);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur Tricks the Tooth Fairy','6세~7세','',277);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur''s First Kiss','6세~7세','',278);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur''s Fire Driil','6세~7세','',279);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur and the School Pet','6세~7세','',280);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur''s Science Fair Trouble','6세~7세','',281);
insert into public.home_books(series,title,age,pref,sort) values ('Arthur','Arthur Loses a Friend','6세~7세','',282);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','I Am Not a Copycat!','','',283);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Doing the Animal Bop','','',284);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','We''re Not Sleepy','','',285);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','If You''re Happy and You Know It!','','',286);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Animal Music','','',287);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Whoosh Around the Mulberry Bush','','',288);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','I Totally, Absolutely, Must Do Homework Now!','','',289);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','You Make Me Smile','','',290);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Betty Goes Bananas','','',291);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','This Book Just Ate My Dog!','','',292);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Over in the Clover','','',293);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Wheels on the Bus','','',294);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','You Can Do It, Lola!','','',295);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Wobble Bear Says Yellow','','',296);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','My Cat Just Sleeps','','',297);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Small Bunny''s Blue Blanket','','',298);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Little Owl''s Orange Scarf','','',299);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Good Moos!','','',300);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','If We Had a Sailboat','','',301);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Puddle''s Big Step','','',302);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Hurry Up, Slow Down!','','',303);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Big Big Big','','',304);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Hare and the Tortoise','','',305);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Pond Goose','','',306);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Little Frog''s Tadpole Trouble','','',307);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Pigeon Pie','','',308);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','From Baby','','',309);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Small Elephant''s Bathtime','','',310);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Cat and Rat Are Friends','','',311);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Lion and the Rat','','',312);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Christopher Nibble','','',313);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Wobble Bear Says Yellow','','',314);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Little by Little','','',315);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','How Many Sleeps?','','',316);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Quack Quack Moo We See You!','','',317);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Somebody Bigger','','',318);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Christopher''s Caterpillars','','',319);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Chicken Can''t See in the Dark','','',320);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Steady, Ghost, Ready','','',321);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','I Love My Cloth','','',322);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Scruff Sheep','','',323);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Noisiest Night','','',324);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Just Like Tonight','','',325);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','What Small Rabbit Heard','','',326);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Pockets Christmas Wish','','',327);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Naughty Toes','','',328);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Goat and Donkey in Strawberry Sunglasses','','',329);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Little Apple Goat','','',330);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Bramble the Brave','','',331);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Christopher''s Bicycle','','',332);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Cowboy Ted and the Messy Toy Room','','',333);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Little Lost','','',334);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Boris Gets Spots','','',335);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Moon in My Room','','',336);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Boris Goes Camping','','',337);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Ayobami and the Names of the Animals','','',338);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Bug and Bear','','',339);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Goat and Donkey and the Great Big Treasure Hunt','','',340);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Little Dog','','',341);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Boris Saves the Show','','',342);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Max and Sadie','','',343);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Too Small for My Big Bed','','',344);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Hugh Shampoo','','',345);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Cowboy Ted and the Scary Night','','',346);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Fish Who Could Wish','','',347);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Professor Puffendorf''s Secret Potions','','',348);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','Sanji and the Baker','','',349);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Great Big Especially Beautiful Easter Egg','','',350);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Duck with No Luck','','',351);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','The Dog Who Could Dig','','',352);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','A Cat Called Scratch','','',353);
insert into public.home_books(series,title,age,pref,sort) values ('ORP','When Chico Went Fishing','','',354);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','I will Love You Forever','','',355);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Hiding Phil','','',356);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Over in the Meadow','','',357);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','There was an old lady who swallowed a fly','','5',358);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','yo! yes?','','',359);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','It''s Christmas, David!','','',360);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Fox and Squirrel','','',361);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Scrribble','','',362);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','My Daddy ate an Apple','','',363);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Grumpy Bird','','',364);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','A PET FOR FLY GUY','','',365);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Gifts','','',366);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','When Sopie gets angry Really, Really Angry...','','',367);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Is Your Mama a Llama?','','',368);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','How Do Dinosaurs Stay SAFE?','','',369);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','DUCK ON a Bike','','',370);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Wonderful Book','','',371);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','GroovyJoe','','',372);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','King of the ZOO','','',373);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','NEE NAW','','',374);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','MAYBE TOMORROW?','','',375);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','the CopyCat','','',376);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Believe it or not my brother has a monster!','','',377);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Pluto visits earth!','','',378);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','WANDERING OFF','','',379);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Zen Shorts','','',380);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','THe very Noisy Bear','','',381);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','Frida','','',382);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','The Dinky Donkey','','',383);
insert into public.home_books(series,title,age,pref,sort) values ('스콜라스틱 픽쳐북 콜렉션','The First Journey','','',384);
insert into public.home_books(series,title,age,pref,sort) values ('단권','no!(Tracey Corderoy)','','',385);
insert into public.home_books(series,title,age,pref,sort) values ('단권','I need my monster','','',386);
insert into public.home_books(series,title,age,pref,sort) values ('단권','I SPY phonics fun','','',387);
insert into public.home_books(series,title,age,pref,sort) values ('단권','little blue and little yellow','','',388);
insert into public.home_books(series,title,age,pref,sort) values ('단권','alphabet city','','',389);
insert into public.home_books(series,title,age,pref,sort) values ('단권','creepy carrots','','',390);
insert into public.home_books(series,title,age,pref,sort) values ('단권','spells-a-popping granny''s shoppong','','',391);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','The Rainbow Fish - OPPOSITES','','',392);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','The Rainbow Fish - COLORS','','',393);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','The Rainbow Fish - COUNTING','','',394);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','The Rainbow Fish Discovers the Deep See','','',395);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','The Rainbow Fish and the sea bonsters'' cave','','',396);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','Rainbow Fish to the rescue','','',397);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','The rainbow fish and the big blue whale','','',398);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','The rainbow fish','','',399);
insert into public.home_books(series,title,age,pref,sort) values ('the Rainbow fish','Good night, little rainbow fish','','',400);
insert into public.home_books(series,title,age,pref,sort) values ('세트 (박스)','NATIONAL GEOGRAPHIC Kids - Pre-reader (30권)','','',1401);
insert into public.home_books(series,title,age,pref,sort) values ('세트 (박스)','Numberblocks 대본 S1/S2 (30권)','','',1402);
insert into public.home_books(series,title,age,pref,sort) values ('세트 (박스)','Wise Picture Dictionary (3권)','','',1403);
insert into public.home_books(series,title,age,pref,sort) values ('세트 (박스)','ORT','','',1404);
