-- 스터디 books에 형태(format)+AR(추정) 추가 (비파괴: theme_key+title 매칭 update)
alter table public.books add column if not exists format text default '';
alter table public.books add column if not exists ar real;

update public.books set format='플랩', ar=null where theme_key='animals' and title='Dear Zoo';
update public.books set format='', ar=3.1 where theme_key='animals' and title='Giraffes Can''t Dance';
update public.books set format='', ar=1.5 where theme_key='animals' and title='Brown Bear, Brown Bear, What Do You See?';
update public.books set format='', ar=2.7 where theme_key='animals' and title='Interrupting Chicken';
update public.books set format='', ar=2.5 where theme_key='animals' and title='The Crocodile Who Didn''t Like Water';
update public.books set format='놀이북', ar=null where theme_key='vehicles' and title='Fire Engine';
update public.books set format='', ar=2.0 where theme_key='vehicles' and title='Truck Full of Ducks';
update public.books set format='', ar=2.2 where theme_key='vehicles' and title='Little Blue Truck';
update public.books set format='', ar=1.3 where theme_key='vehicles' and title='Don''t Let the Pigeon Drive the Bus!';
update public.books set format='', ar=3.1 where theme_key='vehicles' and title='Goodnight, Goodnight, Construction Site';
update public.books set format='플랩', ar=null where theme_key='food' and title='Ketchup on Your Cornflakes?';
update public.books set format='', ar=2.0 where theme_key='food' and title='Jamberry';
update public.books set format='', ar=2.0 where theme_key='food' and title='Today Is Monday';
update public.books set format='', ar=1.3 where theme_key='food' and title='The Watermelon Seed';
update public.books set format='', ar=2.6 where theme_key='food' and title='I Will Not Ever Never Eat a Tomato';
update public.books set format='놀이북', ar=null where theme_key='colors' and title='Mix It Up!';
update public.books set format='', ar=1.5 where theme_key='colors' and title='Mary Wore Her Red Dress';
update public.books set format='', ar=1.2 where theme_key='colors' and title='Where Is the Green Sheep?';
update public.books set format='', ar=3.8 where theme_key='colors' and title='The Day the Crayons Quit';
update public.books set format='', ar=1.5 where theme_key='colors' and title='Pete the Cat: I Love My White Shoes';
update public.books set format='놀이북', ar=null where theme_key='numbers' and title='There Were Ten in the Bed';
update public.books set format='', ar=1.0 where theme_key='numbers' and title='Ten Fat Sausages';
update public.books set format='', ar=2.0 where theme_key='numbers' and title='Ten Black Dots';
update public.books set format='', ar=1.5 where theme_key='numbers' and title='Ten Apples Up on Top!';
update public.books set format='', ar=1.8 where theme_key='numbers' and title='Five Little Monkeys Jumping on the Bed';
update public.books set format='플랩', ar=null where theme_key='family' and title='Where Is Baby''s Mommy?';
update public.books set format='', ar=2.4 where theme_key='family' and title='Is Your Mama a Llama?';
update public.books set format='', ar=3.0 where theme_key='family' and title='Guess How Much I Love You';
update public.books set format='', ar=2.5 where theme_key='family' and title='My Mum';
update public.books set format='', ar=2.0 where theme_key='family' and title='Peppa Pig: Peppa Goes Swimming';
update public.books set format='플랩', ar=null where theme_key='bedtime' and title='Tuck Me In!';
update public.books set format='', ar=2.4 where theme_key='bedtime' and title='The Going to Bed Book';
update public.books set format='', ar=1.8 where theme_key='bedtime' and title='Goodnight Moon';
update public.books set format='', ar=1.8 where theme_key='bedtime' and title='Llama Llama Red Pajama';
update public.books set format='', ar=2.5 where theme_key='bedtime' and title='A Big Mooncake for Little Star';
update public.books set format='팝업', ar=null where theme_key='feelings' and title='The Color Monster: A Pop-Up Book of Feelings';
update public.books set format='', ar=2.5 where theme_key='feelings' and title='The Way I Feel';
update public.books set format='', ar=2.0 where theme_key='feelings' and title='It''s Okay to Be Different';
update public.books set format='', ar=2.5 where theme_key='feelings' and title='The Bad Seed';
update public.books set format='', ar=2.2 where theme_key='feelings' and title='Knuffle Bunny: A Cautionary Tale';
update public.books set format='플랩', ar=null where theme_key='body' and title='Where Is Baby''s Belly Button?';
update public.books set format='', ar=1.5 where theme_key='body' and title='Here Are My Hands';
update public.books set format='', ar=1.3 where theme_key='body' and title='From Head to Toe';
update public.books set format='', ar=1.5 where theme_key='body' and title='Belly Button Book';
update public.books set format='', ar=1.8 where theme_key='body' and title='Ten Little Fingers and Ten Little Toes';
update public.books set format='놀이북', ar=null where theme_key='bugs' and title='The Very Busy Spider';
update public.books set format='', ar=3.0 where theme_key='bugs' and title='Superworm';
update public.books set format='', ar=2.9 where theme_key='bugs' and title='The Very Hungry Caterpillar';
update public.books set format='', ar=2.9 where theme_key='bugs' and title='The Grouchy Ladybug';
update public.books set format='', ar=3.0 where theme_key='bugs' and title='The Very Quiet Cricket';
update public.books set format='놀이북', ar=null where theme_key='dinosaurs' and title='That''s Not My Dinosaur';
update public.books set format='', ar=1.0 where theme_key='dinosaurs' and title='Dinosaur Roar!';
update public.books set format='', ar=2.7 where theme_key='dinosaurs' and title='How Do Dinosaurs Say Goodnight?';
update public.books set format='', ar=1.3 where theme_key='dinosaurs' and title='Dinosaur vs. Bedtime';
update public.books set format='', ar=3.5 where theme_key='dinosaurs' and title='Tyrannosaurus Drip';
update public.books set format='놀이북', ar=null where theme_key='nature' and title='Tap the Magic Tree';
update public.books set format='', ar=3.5 where theme_key='nature' and title='Stick Man';
update public.books set format='', ar=1.9 where theme_key='nature' and title='The Carrot Seed';
update public.books set format='', ar=2.5 where theme_key='nature' and title='The Leaf Thief';
update public.books set format='', ar=3.5 where theme_key='nature' and title='The Snail and the Whale';
update public.books set format='플랩', ar=null where theme_key='weather-seasons' and title='Maisy''s Wonderful Weather Book';
update public.books set format='', ar=1.5 where theme_key='weather-seasons' and title='Rain!';
update public.books set format='', ar=1.6 where theme_key='weather-seasons' and title='It Looked Like Spilt Milk';
update public.books set format='', ar=3.5 where theme_key='weather-seasons' and title='Snowmen at Night';
update public.books set format='', ar=2.7 where theme_key='weather-seasons' and title='The Snowy Day';
update public.books set format='플랩', ar=null where theme_key='pets' and title='Where''s Spot?';
update public.books set format='', ar=3.0 where theme_key='pets' and title='Hairy Maclary from Donaldson''s Dairy';
update public.books set format='', ar=1.1 where theme_key='pets' and title='Go, Dog. Go!';
update public.books set format='', ar=1.7 where theme_key='pets' and title='Bark, George';
update public.books set format='', ar=2.5 where theme_key='pets' and title='Hot Dog';
update public.books set format='팝업', ar=null where theme_key='farm' and title='Charlie Chick';
update public.books set format='', ar=2.0 where theme_key='farm' and title='Barnyard Dance';
update public.books set format='', ar=1.6 where theme_key='farm' and title='Mrs. Wishy-Washy';
update public.books set format='', ar=3.7 where theme_key='farm' and title='Click, Clack, Moo: Cows That Type';
update public.books set format='', ar=3.2 where theme_key='farm' and title='The Little Red Hen';
update public.books set format='놀이북', ar=null where theme_key='ocean' and title='One Lonely Fish';
update public.books set format='', ar=2.8 where theme_key='ocean' and title='The Pout-Pout Fish';
update public.books set format='', ar=1.5 where theme_key='ocean' and title='Hooray for Fish!';
update public.books set format='', ar=1.6 where theme_key='ocean' and title='This Is Not My Hat';
update public.books set format='', ar=3.2 where theme_key='ocean' and title='Swimmy';
update public.books set format='놀이북', ar=null where theme_key='monsters' and title='Go Away, Big Green Monster!';
update public.books set format='', ar=2.9 where theme_key='monsters' and title='The Gruffalo';
update public.books set format='', ar=1.5 where theme_key='monsters' and title='If You''re a Monster and You Know It';
update public.books set format='', ar=2.6 where theme_key='monsters' and title='The Monster at the End of This Book';
update public.books set format='', ar=3.4 where theme_key='monsters' and title='Where the Wild Things Are';
update public.books set format='플랩', ar=null where theme_key='halloween' and title='Where Is Baby''s Pumpkin?';
update public.books set format='', ar=3.0 where theme_key='halloween' and title='Room on the Broom';
update public.books set format='', ar=3.3 where theme_key='halloween' and title='The Little Old Lady Who Was Not Afraid of Anything';
update public.books set format='', ar=3.1 where theme_key='halloween' and title='Creepy Carrots!';
update public.books set format='', ar=1.9 where theme_key='halloween' and title='Skeleton Hiccups';
update public.books set format='플랩', ar=null where theme_key='christmas' and title='Dear Santa';
update public.books set format='', ar=4.0 where theme_key='christmas' and title='The Night Before Christmas';
update public.books set format='', ar=3.5 where theme_key='christmas' and title='The Twelve Days of Christmas';
update public.books set format='', ar=4.0 where theme_key='christmas' and title='How the Grinch Stole Christmas!';
update public.books set format='', ar=4.0 where theme_key='christmas' and title='The Polar Express';
update public.books set format='놀이북', ar=null where theme_key='songs-rhymes' and title='The Wheels on the Bus';
update public.books set format='', ar=1.5 where theme_key='songs-rhymes' and title='Walking Through the Jungle';
update public.books set format='', ar=1.5 where theme_key='songs-rhymes' and title='Polar Bear, Polar Bear, What Do You Hear?';
update public.books set format='', ar=1.9 where theme_key='songs-rhymes' and title='There''s a Wocket in My Pocket!';
update public.books set format='', ar=3.0 where theme_key='songs-rhymes' and title='Over in the Meadow';
update public.books set format='플랩', ar=null where theme_key='school-friends' and title='Spot Goes to School';
update public.books set format='', ar=2.4 where theme_key='school-friends' and title='Llama Llama Misses Mama';
update public.books set format='', ar=0.9 where theme_key='school-friends' and title='Do You Want to Be My Friend?';
update public.books set format='', ar=3.2 where theme_key='school-friends' and title='We Don''t Eat Our Classmates';
update public.books set format='', ar=3.2 where theme_key='school-friends' and title='Chrysanthemum';
update public.books set format='팝업', ar=null where theme_key='daily-routine' and title='Brush Your Teeth, Please';
update public.books set format='', ar=2.0 where theme_key='daily-routine' and title='Pajama Time!';
update public.books set format='', ar=2.9 where theme_key='daily-routine' and title='The Napping House';
update public.books set format='', ar=0.8 where theme_key='daily-routine' and title='No, David!';
update public.books set format='', ar=0.9 where theme_key='daily-routine' and title='Bathtime for Biscuit';
update public.books set format='놀이북', ar=null where theme_key='opposites-concepts' and title='Press Here';
update public.books set format='', ar=2.5 where theme_key='opposites-concepts' and title='Round Is a Mooncake';
update public.books set format='', ar=1.0 where theme_key='opposites-concepts' and title='Opposites';
update public.books set format='', ar=1.6 where theme_key='opposites-concepts' and title='I Want My Hat Back';
update public.books set format='', ar=2.1 where theme_key='opposites-concepts' and title='They All Saw a Cat';
update public.books set format='놀이북', ar=null where theme_key='imagination' and title='Don''t Push the Button!';
update public.books set format='', ar=3.5 where theme_key='imagination' and title='If I Built a House';
update public.books set format='', ar=0.7 where theme_key='imagination' and title='Not a Box';
update public.books set format='', ar=2.6 where theme_key='imagination' and title='Sam & Dave Dig a Hole';
update public.books set format='', ar=3.0 where theme_key='imagination' and title='Harold and the Purple Crayon';
