# -*- coding: utf-8 -*-
"""조작북 형태(FORMAT) + AR(추정) 데이터. build_challenge.py 와 패치 스크립트가 공유."""
import re
def norm(s): return re.sub(r"[^a-z0-9]+", " ", (s or "").lower()).strip()

# 조작북 24권 형태: 팝업 / 플랩 / 놀이북
_FORMAT = {
 "The Color Monster: A Pop-Up Book of Feelings": "팝업",
 "Charlie Chick": "팝업",
 "Brush Your Teeth, Please": "팝업",
 "Dear Zoo": "플랩",
 "Ketchup on Your Cornflakes?": "플랩",
 "Where Is Baby's Mommy?": "플랩",
 "Tuck Me In!": "플랩",
 "Where Is Baby's Belly Button?": "플랩",
 "Maisy's Wonderful Weather Book": "플랩",
 "Where's Spot?": "플랩",
 "Where Is Baby's Pumpkin?": "플랩",
 "Dear Santa": "플랩",
 "Spot Goes to School": "플랩",
 "Fire Engine": "놀이북",
 "There Were Ten in the Bed": "놀이북",
 "The Very Busy Spider": "놀이북",
 "That's Not My Dinosaur": "놀이북",
 "Mix It Up!": "놀이북",
 "Tap the Magic Tree": "놀이북",
 "One Lonely Fish": "놀이북",
 "Go Away, Big Green Monster!": "놀이북",
 "The Wheels on the Bus": "놀이북",
 "Press Here": "놀이북",
 "Don't Push the Button!": "놀이북",
}

# 나머지 96권 AR(ATOS BL, 추정). 유명 고전은 공개값, 일부는 어림값.
_AR = {
 "Giraffes Can't Dance": 3.1, "Brown Bear, Brown Bear, What Do You See?": 1.5,
 "Interrupting Chicken": 2.7, "The Crocodile Who Didn't Like Water": 2.5,
 "Little Blue Truck": 2.2, "Truck Full of Ducks": 2.0,
 "Don't Let the Pigeon Drive the Bus!": 1.3, "Goodnight, Goodnight, Construction Site": 3.1,
 "Jamberry": 2.0, "Today Is Monday": 2.0, "The Watermelon Seed": 1.3,
 "I Will Not Ever Never Eat a Tomato": 2.6,
 "Mary Wore Her Red Dress": 1.5, "Where Is the Green Sheep?": 1.2,
 "The Day the Crayons Quit": 3.8, "Pete the Cat: I Love My White Shoes": 1.5,
 "Ten Fat Sausages": 1.0, "Ten Black Dots": 2.0, "Ten Apples Up on Top!": 1.5,
 "Five Little Monkeys Jumping on the Bed": 1.8,
 "Is Your Mama a Llama?": 2.4, "Guess How Much I Love You": 3.0, "My Mum": 2.5,
 "Peppa Pig: Peppa Goes Swimming": 2.0,
 "The Going to Bed Book": 2.4, "Goodnight Moon": 1.8, "Llama Llama Red Pajama": 1.8,
 "A Big Mooncake for Little Star": 2.5,
 "The Way I Feel": 2.5, "It's Okay to Be Different": 2.0, "The Bad Seed": 2.5,
 "Knuffle Bunny: A Cautionary Tale": 2.2,
 "Here Are My Hands": 1.5, "From Head to Toe": 1.3, "Belly Button Book": 1.5,
 "Ten Little Fingers and Ten Little Toes": 1.8,
 "Superworm": 3.0, "The Very Hungry Caterpillar": 2.9, "The Grouchy Ladybug": 2.9,
 "The Very Quiet Cricket": 3.0,
 "Dinosaur Roar!": 1.0, "How Do Dinosaurs Say Goodnight?": 2.7,
 "Dinosaur vs. Bedtime": 1.3, "Tyrannosaurus Drip": 3.5,
 "Stick Man": 3.5, "The Carrot Seed": 1.9, "The Leaf Thief": 2.5,
 "The Snail and the Whale": 3.5,
 "Rain!": 1.5, "It Looked Like Spilt Milk": 1.6, "Snowmen at Night": 3.5,
 "The Snowy Day": 2.7,
 "Hairy Maclary from Donaldson's Dairy": 3.0, "Go, Dog. Go!": 1.1,
 "Bark, George": 1.7, "Hot Dog": 2.5,
 "Barnyard Dance": 2.0, "Mrs. Wishy-Washy": 1.6, "Click, Clack, Moo: Cows That Type": 3.7,
 "The Little Red Hen": 3.2,
 "The Pout-Pout Fish": 2.8, "Hooray for Fish!": 1.5, "This Is Not My Hat": 1.6,
 "Swimmy": 3.2,
 "The Gruffalo": 2.9, "If You're a Monster and You Know It": 1.5,
 "The Monster at the End of This Book": 2.6, "Where the Wild Things Are": 3.4,
 "Room on the Broom": 3.0, "The Little Old Lady Who Was Not Afraid of Anything": 3.3,
 "Creepy Carrots!": 3.1, "Skeleton Hiccups": 1.9,
 "The Night Before Christmas": 4.0, "The Twelve Days of Christmas": 3.5,
 "How the Grinch Stole Christmas!": 4.0, "The Polar Express": 4.0,
 "Walking Through the Jungle": 1.5, "Polar Bear, Polar Bear, What Do You Hear?": 1.5,
 "There's a Wocket in My Pocket!": 1.9, "Over in the Meadow": 3.0,
 "Llama Llama Misses Mama": 2.4, "Do You Want to Be My Friend?": 0.9,
 "We Don't Eat Our Classmates": 3.2, "Chrysanthemum": 3.2,
 "Pajama Time!": 2.0, "The Napping House": 2.9, "No, David!": 0.8,
 "Bathtime for Biscuit": 0.9,
 "Round Is a Mooncake": 2.5, "Opposites": 1.0, "I Want My Hat Back": 1.6,
 "They All Saw a Cat": 2.1,
 "If I Built a House": 3.5, "Not a Box": 0.7, "Sam & Dave Dig a Hole": 2.6,
 "Harold and the Purple Crayon": 3.0,
}

FORMAT = {norm(k): v for k, v in _FORMAT.items()}
AR = {norm(k): v for k, v in _AR.items()}
