# -*- coding: utf-8 -*-
"""국내 서점 통합순위 100 + 수상 정보 (build_site.py / build_challenge.py 공용)"""
# (rank, 표시명, 검색용 영문제목, 권장연령, 특징)
DOMESTIC_ALL = [
(1,"Peppa Pig 시리즈","Peppa Pig","2~6","3채널 1위급 스테디"),
(2,"The Color Monster (감정 팝업)","The Color Monster","3~6","감정교육 대표"),
(3,"Don't Push the Button!","Don't Push the Button","2~5","인터랙티브"),
(4,"Ketchup on Your Cornflakes?","Ketchup on Your Cornflakes","2~6","플랩북"),
(5,"The Watermelon Seed","The Watermelon Seed","3~6","가이젤상"),
(6,"Maisy 시리즈","Maisy","2~5","조작북 다수"),
(7,"No, David! / David 시리즈","No David","3~6","쉬움(AR0.9)"),
(8,"Piggybook","Piggybook","4~8","앤서니 브라운"),
(9,"The Dot","The Dot","5~9","피터 레이놀즈"),
(10,"Skeleton Hiccups","Skeleton Hiccups","3~7","핼러윈"),
(11,"Where's Wally? 세트","Where's Wally","5~9","찾기놀이"),
(12,"Mo Willems: Pigeon 시리즈","Don't Let the Pigeon Drive the Bus","3~7","유머 대표"),
(13,"Elephant & Piggie 시리즈","There Is a Bird on Your Head","4~7","리더스 겸용(AR1.1)"),
(14,"Pete the Cat: I Love My White Shoes","Pete the Cat I Love My White Shoes","3~6","노래책"),
(15,"Dear Zoo","Dear Zoo","1~4","저연령 필수 플랩"),
(16,"Library Lion","Library Lion","4~8","AR2.8"),
(17,"Truck Full of Ducks","Truck Full of Ducks","3~6","AR1.4"),
(18,"Knuffle Bunny 세트","Knuffle Bunny","2~6","칼데콧 아너"),
(19,"노부영 Baby 세트 (Choo Choo 등)","Choo Choo","0~3","노래·조작"),
(20,"Froggy 시리즈","Froggy Gets Dressed","4~8","AR1.8~2.6"),
(21,"600 Black Spots","600 Black Spots","2~6","인터랙티브 팝업"),
(22,"I Will Not Ever Never Eat a Tomato","I Will Not Ever Never Eat a Tomato","3~7","찰리와 롤라·편식"),
(23,"Meg and Mog","Meg and Mog","4~8","AR2.5"),
(24,"Indestructibles 츄잉북","Indestructibles","0~2","찢김X·세탁O"),
(25,"The Giving Tree","The Giving Tree","5~9","쉘 실버스타인"),
(26,"Last Stop on Market Street","Last Stop on Market Street","5~9","뉴베리 대상"),
(27,"The Grouchy Ladybug","The Grouchy Ladybug","3~7","에릭 칼"),
(28,"My Lucky Day","My Lucky Day","4~8","AR2.3"),
(29,"Shark in the Park","Shark in the Park","3~6","AR1.3"),
(30,"Interrupting Chicken","Interrupting Chicken","4~8","칼데콧 아너"),
(31,"A Big Mooncake for Little Star","A Big Mooncake for Little Star","3~7","칼데콧 아너"),
(32,"The Gardener","The Gardener","5~9","AR3.9"),
(33,"The Crocodile Who Didn't Like Water","The Crocodile Who Didn't Like Water","3~7","AR2.0"),
(34,"Thank You, Mr. Falker","Thank You Mr Falker","6~9","난독증 성장"),
(35,"Brown Bear, Brown Bear, What Do You See?","Brown Bear Brown Bear What Do You See","1~4","에릭 칼·노부영"),
(36,"From Head to Toe","From Head to Toe","2~5","에릭 칼·신체"),
(37,"Today Is Monday","Today Is Monday","2~5","에릭 칼·요일"),
(38,"Polar Bear, Polar Bear, What Do You Hear?","Polar Bear Polar Bear What Do You Hear","1~4","에릭 칼"),
(39,"Press Here","Press Here","3~6","인터랙티브 명작"),
(40,"Go Away, Big Green Monster!","Go Away Big Green Monster","2~5","감정·공포 극복"),
(41,"Where the Wild Things Are","Where the Wild Things Are","4~8","1964 칼데콧"),
(42,"This Is Not My Hat","This Is Not My Hat","4~8","2013 칼데콧"),
(43,"Sam and Dave Dig a Hole","Sam and Dave Dig a Hole","4~8","2015 칼데콧 아너"),
(44,"Creepy Carrots!","Creepy Carrots","4~8","2013 칼데콧 아너"),
(45,"My Dad / My Mum","My Mum","3~7","앤서니 브라운"),
(46,"The True Story of the 3 Little Pigs","The True Story of the 3 Little Pigs","5~9","패러디 명작"),
(47,"Doctor De Soto","Doctor De Soto","5~9","1983 뉴베리 아너"),
(48,"That Is Not a Good Idea!","That Is Not a Good Idea","4~7","모 윌렘스"),
(49,"Frog and Toad 시리즈","Frog and Toad Are Friends","5~8","뉴베리 아너·리더스"),
(50,"Hi! Fly Guy","Hi Fly Guy","4~7","가이젤 아너·리더스"),
(51,"The Very Hungry Caterpillar","The Very Hungry Caterpillar","2~5","에릭 칼 대표작"),
(52,"The Gruffalo","The Gruffalo","3~7","줄리아 도널드슨"),
(53,"They All Saw a Cat","They All Saw a Cat","4~8","2017 칼데콧 아너"),
(54,"Where's Spot?","Where's Spot","1~4","플랩북 클래식"),
(55,"Kitten's First Full Moon","Kitten's First Full Moon","3~6","2005 칼데콧 메달"),
(56,"Stick Man","Stick Man","3~7","줄리아 도널드슨"),
(57,"I Want My Hat Back","I Want My Hat Back","3~7","존 클라센·가이젤 아너"),
(58,"The Boy, The Mole, The Fox and The Horse","The Boy the Mole the Fox and the Horse","6~9","전연령 감동"),
(59,"Swimmy","Swimmy","4~8","레오 리오니·칼데콧 아너"),
(60,"Where Is the Green Sheep?","Where Is the Green Sheep","1~4","멤 폭스"),
(61,"Mix It Up!","Mix It Up","2~6","에르베 튈레"),
(62,"It's Okay to Be Different","It's Okay to Be Different","3~7","토드 파"),
(63,"Glad Monster, Sad Monster","Glad Monster Sad Monster","3~7","감정"),
(64,"Making Faces: A First Book of Emotions","Making Faces","0~3","보드북"),
(65,"Hot Dog","Hot Dog","3~7","2023 칼데콧 메달"),
(66,"I'm the Biggest Thing in the Ocean!","I'm the Biggest Thing in the Ocean","3~6",""),
(67,"The World of Peter Rabbit 세트","The Tale of Peter Rabbit","4~9","베아트릭스 포터"),
(68,"Bluey 시리즈","Bluey","2~6","인기 애니 원작"),
(69,"Who Would Win? 시리즈","Who Would Win","5~9","논픽션 인기"),
(70,"Peekaboo 시리즈 (Sun 등)","Peekaboo Sun","0~3","잉엘라 아르후니우스"),
(71,"The Leaf Thief","The Leaf Thief","3~7","웬디북 상위"),
(72,"Ten Fat Sausages","Ten Fat Sausages","2~5","노래책"),
(73,"Time to Pee!","Time to Pee","2~5","배변훈련"),
(74,"Knock Knock, Who's There?","Knock Knock Who's There","3~6","플랩북·AR3.0"),
(75,"Cookies! (Cook In A Book)","Cookies Cook in a Book","3~7","조작 요리책"),
(76,"The Happy Little Yellow Box","The Happy Little Yellow Box","2~5","반대말 팝업"),
(77,"Magic School Bus 시리즈","The Magic School Bus","5~9","과학·AR3.6~4.6"),
(78,"Fireworks","Fireworks","3~6",""),
(79,"Vincent Paints His House","Vincent Paints His House","3~6","색·예술"),
(80,"Not Me (StoryPlus QR)","Not Me","3~6",""),
(81,"Little Bear (I Can Read)","Little Bear","4~7","얼리리더 클래식"),
(82,"Amelia Bedelia (I Can Read)","Amelia Bedelia","5~8","얼리리더"),
(83,"Henry and Mudge 시리즈","Henry and Mudge","5~8","얼리리더"),
(84,"Mr. Putter & Tabby 시리즈","Mr. Putter and Tabby","5~8","얼리리더"),
(85,"Mouse Soup","Mouse Soup","4~7","아널드 로벨"),
(86,"Biscuit Phonics 12종 세트","Biscuit Phonics Fun","4~7","파닉스"),
(87,"National Geographic Kids Readers","National Geographic Readers","4~9","논픽션 리더스"),
(88,"Hello, World! 시리즈 (Solar System 등)","Hello World Solar System","2~6","논픽션 보드북"),
(89,"Our Solar System: Science for Toddlers","Our Solar System","1~4",""),
(90,"First 100 Words / Trucks","First 100 Words","0~3","단어 보드북"),
(91,"Miffy 시리즈","Miffy","1~4","딕 브루너"),
(92,"Brush Your Teeth, Please (팝업)","Brush Your Teeth Please","2~5","생활습관 팝업"),
(93,"Goodnight, I Love You","Goodnight I Love You","1~4","베드타임"),
(94,"Ten Tiny Toes","Ten Tiny Toes","0~3",""),
(95,"Encyclopedia Prehistorica: Dinosaurs","Encyclopedia Prehistorica Dinosaurs","5~9","공룡 대형 팝업"),
(96,"Safari: A Photicular Book","Safari A Photicular Book","3~8","움직이는 사진책"),
(97,"No Kimchi For Me!","No Kimchi For Me","3~7","한국문화"),
(98,"Walking Through the Jungle","Walking Through the Jungle","2~5","노래책"),
(99,"How the Grinch Stole Christmas!","How the Grinch Stole Christmas","3~7","크리스마스 시즌"),
(100,"The Jesus Storybook Bible","The Jesus Storybook Bible","4~9","스테디(종교)"),
]

# 국내 리스트 비고에서 뽑은 수상 정보 (norm 제목 -> 배지 라벨)
AWARDS_EXTRA = {
"they all saw a cat":"🏅 칼데콧 아너 2017",
"hot dog":"🥇 칼데콧 메달 2023",
"i want my hat back":"🎖️ 가이젤 아너 2012",
"interrupting chicken":"🏅 칼데콧 아너 2011",
"doctor de soto":"🎖️ 뉴베리 아너 1983",
"frog and toad are friends":"🏅 칼데콧 아너 1971",
"hi fly guy":"🎖️ 가이젤 아너 2006",
"the watermelon seed":"🎖️ 가이젤상 2014",
"swimmy":"🏅 칼데콧 아너 1964",
"kittens first full moon":"🥇 칼데콧 메달 2005",
"last stop on market street":"🎖️ 뉴베리 메달 2016 · 🏅 칼데콧 아너 2016",
"a big mooncake for little star":"🏅 칼데콧 아너 2019",
"knuffle bunny":"🏅 칼데콧 아너 2005",
}
