# -*- coding: utf-8 -*-
"""세계 인기 그림책 100 (여러 서점 통합순위) — build_site.py / build_challenge.py 공용"""
# (rank, title, author)
GLOBAL_100 = [
(1,"The Very Hungry Caterpillar","Eric Carle"),
(2,"The Gruffalo","Julia Donaldson"),
(3,"Brown Bear, Brown Bear, What Do You See?","Bill Martin Jr."),
(4,"The Rainbow Fish","Marcus Pfister"),
(5,"Goodnight Moon","Margaret Wise Brown"),
(6,"Where the Wild Things Are","Maurice Sendak"),
(7,"Dear Zoo","Rod Campbell"),
(8,"Where's Spot?","Eric Hill"),
(9,"Elmer","David McKee"),
(10,"The Tiger Who Came to Tea","Judith Kerr"),
(11,"We're Going on a Bear Hunt","Michael Rosen"),
(12,"Love You Forever","Robert Munsch"),
(13,"Guess How Much I Love You","Sam McBratney"),
(14,"The Giving Tree","Shel Silverstein"),
(15,"I Love You to the Moon and Back","Amelia Hepworth"),
(16,"Llama Llama Red Pajama","Anna Dewdney"),
(17,"Room on the Broom","Julia Donaldson"),
(18,"The Day the Crayons Quit","Drew Daywalt"),
(19,"Little Blue Truck","Alice Schertle"),
(20,"If You Give a Mouse a Cookie","Laura Numeroff"),
(21,"The Leaf Thief","Alice Hemming"),
(22,"Don't Let the Pigeon Drive the Bus!","Mo Willems"),
(23,"The Cat in the Hat","Dr. Seuss"),
(24,"Green Eggs and Ham","Dr. Seuss"),
(25,"Oh, the Places You'll Go!","Dr. Seuss"),
(26,"The Snail and the Whale","Julia Donaldson"),
(27,"Stick Man","Julia Donaldson"),
(28,"Zog","Julia Donaldson"),
(29,"The Tale of Peter Rabbit","Beatrix Potter"),
(30,"Paddington","Michael Bond"),
(31,"Chicka Chicka Boom Boom","Bill Martin Jr."),
(32,"The Wonderful Things You Will Be","Emily Winfield Martin"),
(33,"Ten Little Fingers and Ten Little Toes","Mem Fox"),
(34,"Curious George","H. A. Rey"),
(35,"Chrysanthemum","Kevin Henkes"),
(36,"Corduroy","Don Freeman"),
(37,"Madeline","Ludwig Bemelmans"),
(38,"The Polar Express","Chris Van Allsburg"),
(39,"The Little Engine That Could","Watty Piper"),
(40,"Harold and the Purple Crayon","Crockett Johnson"),
(41,"Good Night, Gorilla","Peggy Rathmann"),
(42,"The Snowy Day","Ezra Jack Keats"),
(43,"Dragons Love Tacos","Adam Rubin"),
(44,"The Pout-Pout Fish","Deborah Diesen"),
(45,"Press Here","Hervé Tullet"),
(46,"The Book with No Pictures","B. J. Novak"),
(47,"Goodnight, Goodnight, Construction Site","Sherri Duskey Rinker"),
(48,"Pete the Cat: I Love My White Shoes","James Dean"),
(49,"The Snowman","Raymond Briggs"),
(50,"Funnybones","Janet Ahlberg"),
(51,"Hairy Maclary from Donaldson's Dairy","Lynley Dodd"),
(52,"Giraffes Can't Dance","Giles Andreae"),
(53,"The Highway Rat","Julia Donaldson"),
(54,"Monkey Puzzle","Julia Donaldson"),
(55,"Superworm","Julia Donaldson"),
(56,"The Smeds and the Smoos","Julia Donaldson"),
(57,"The Baddies","Julia Donaldson"),
(58,"There's a Ghost in this House","Oliver Jeffers"),
(59,"Lost and Found","Oliver Jeffers"),
(60,"How to Catch a Star","Oliver Jeffers"),
(61,"Knuffle Bunny","Mo Willems"),
(62,"I Want My Hat Back","Jon Klassen"),
(63,"This Is Not My Hat","Jon Klassen"),
(64,"The Bad Seed","Jory John"),
(65,"The Good Egg","Jory John"),
(66,"After the Fall","Dan Santat"),
(67,"The Rabbit Listened","Cori Doerrfeld"),
(68,"Last Stop on Market Street","Matt de la Peña"),
(69,"The Invisible String","Patrice Karst"),
(70,"On the Night You Were Born","Nancy Tillman"),
(71,"The Napping House","Audrey Wood"),
(72,"Swimmy","Leo Lionni"),
(73,"Frederick","Leo Lionni"),
(74,"Moo, Baa, La La La!","Sandra Boynton"),
(75,"The Going-to-Bed Book","Sandra Boynton"),
(76,"Polar Bear, Polar Bear, What Do You Hear?","Bill Martin Jr."),
(77,"From Head to Toe","Eric Carle"),
(78,"The Very Busy Spider","Eric Carle"),
(79,"The Color Monster","Anna Llenas"),
(80,"Kitten's First Full Moon","Kevin Henkes"),
(81,"Caps for Sale","Esphyr Slobodkina"),
(82,"How to Catch a Dinosaur","Adam Wallace"),
(83,"How to Catch a Unicorn","Adam Wallace"),
(84,"See You Later, Alligator","Sally Hopgood"),
(85,"Gorilla","Anthony Browne"),
(86,"Dogger","Shirley Hughes"),
(87,"Supertato","Sue Hendra"),
(88,"The Dinosaur That Pooped a Football","Tom Fletcher"),
(89,"You Choose","Pippa Goodhart"),
(90,"The Day the Crayons Made Friends","Drew Daywalt"),
(91,"Gruffalo Granny","Julia Donaldson"),
(92,"The Complete Tales of Winnie-the-Pooh","A. A. Milne"),
(93,"Bluey: The Sleepover","Bluey"),
(94,"Ten Minutes to Bed: Little Bear","Rhiannon Fielding"),
(95,"You Can't Take an Elephant into School","Patricia Cleveland-Peck"),
(96,"I Love You Like No Otter","Rose Rossner"),
(97,"Little Blue Truck's Halloween","Alice Schertle"),
(98,"Make Way for Ducklings","Robert McCloskey"),
(99,"We're All Wonders","R. J. Palacio"),
(100,"Julián Is a Mermaid","Jessica Love"),
]
